App2 - Pagination issue after searching for a form
AOT-Technologies/forms-flow-ai pull request #1171
Opened 2023-01-19 07:29 UTC by Josephalexantony-aot

# Issue Tracking

JIRA:  https://aottech.atlassian.net/browse/FWF-1982
Issue Type: BUG/ FEATURE

# Changes

Login to app2 and search for a form.
Select All from the drop down.
Close the searched result and  if the number of previous search result was not being cleard. 
if it was 1 in search, then the number of forms after closing the search was also the same. 

fix. changed the limit to defaul(5) in the onClear fucntion.

# How has the change been tested?

# Screenshots (if applicable)

#not a ui issue. 

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2023-01-23 06:02 UTC, abhilash-aot approved these changes

2023-01-23 14:18 UTC, abilpraju-aot approved these changes

2023-01-23 14:33 UTC, sreehari-aot approved these changes

2023-01-24 05:23 UTC, shuhaib-aot requested changes

2023-01-24 05:23 UTC, shuhaib-aot commented on forms-flow-web/src/components/Form/List.js
> +    dispatch(setBPMFormLimit(5));
My opinion here we don't want to ```dispatch(setBPMFormLimit(5));``` statically  you can use ```dispatch(setBPMFormLimit(limit));```

2023-01-24 05:34 UTC, shuhaib-aot approved these changes

2023-01-24 07:19 UTC, merged