anonymous form copy with protocol.
AOT-Technologies/forms-flow-ai pull request #1173
Opened 2023-01-20 05:32 UTC by Josephalexantony-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-1728
Issue Type: BUG/ FEATURE

# Changes

Added the protocol with copied url. 

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2023-01-20 07:48 UTC, shuhaib-aot approved these changes

2023-01-20 07:50 UTC, shuhaib-aot requested changes
use this ```window.origin ```instead of window.location.host and window.location.protocol

2023-01-23 04:51 UTC, shuhaib-aot approved these changes
LGTM

2023-01-23 04:55 UTC, abilpraju-aot approved these changes

2023-01-23 04:55 UTC, AbijithS-aot approved these changes

2023-01-23 05:01 UTC, abhilash-aot approved these changes

2023-01-23 05:01 UTC, merged