06/07develop
AOT-Technologies/forms-flow-ai pull request #120
Opened 2021-07-06 15:40 UTC by kurianbenoy-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2021-07-06 15:48 UTC, abhilash-aot requested changes

2021-07-06 15:48 UTC, abhilash-aot commented on forms-flow-api/src/api/utils/constants.py
> +>>>>>>> d6193976573a24f5bb6f02b70b1dbe2e246f0a3d
Why is there conflict?

2021-07-06 15:53 UTC, kurianbenoy-aot commented on forms-flow-api/src/api/utils/constants.py
> +>>>>>>> d6193976573a24f5bb6f02b70b1dbe2e246f0a3d
Resolved

2021-07-06 16:02 UTC, sumathi-thirumani-aot approved these changes

2021-07-06 16:05 UTC, sumathi-thirumani-aot requested changes
@shibin-aot Please remove the global import of packages

2021-07-06 16:50 UTC, shibin-aot commented
The changes will be taken later, since the intention of the review comment is not clear. As this change doesn't impact any functionality nor the performance let us make this change later.

2021-07-06 17:12 UTC, abhilash-aot approved these changes

2021-07-07 00:54 UTC, shibin-aot approved these changes

2021-07-07 04:44 UTC, abhilash-aot approved these changes

2021-07-07 04:44 UTC, merged

2021-07-07 04:45 UTC, kurianbenoy-aot commented on forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/BPMFormDataPipelineListener.java
> +import org.camunda.bpm.engine.delegate.DelegateExecution;
The requested changes have been made by @shibin-aot