Config cleanup
AOT-Technologies/forms-flow-ai pull request #1401
Opened 2023-04-17 12:18 UTC by sreehari-aot

2023-04-17 14:02 UTC, shuhaib-aot requested changes

2023-04-17 14:02 UTC, shuhaib-aot commented on deployment/docker/sample.env
> +ENABLE_FORMS_MODULE=
we can comment these variable

2023-04-17 14:02 UTC, shuhaib-aot commented on forms-flow-web-root-config/sample.env
>  MF_FORMSFLOW_WEB_URL=
here also we can comment env variable

2023-05-15 04:14 UTC, shuhaib-aot approved these changes

2023-05-15 04:32 UTC, abhilash-aot approved these changes
@abilpraju-aot / @kiran-aot / @alanraju-aot / @amal-k-soman-aot devops team have a check with the environment changes for form bundling deployment

2023-05-15 04:33 UTC, merged