RBAC functionalities
AOT-Technologies/forms-flow-ai pull request #1409
Opened 2023-04-24 14:30 UTC by abilpraju-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE
https://aottech.atlassian.net/browse/FWF-1907
https://aottech.atlassian.net/browse/FWF-2125
![image](https://user-images.githubusercontent.com/83952803/234027291-a3287942-79ea-4365-ad7f-00c1c00aba9a.png)
![image](https://user-images.githubusercontent.com/83952803/231523604-526758fd-075f-458b-b7db-ac884f0b845c.png)
![image](https://user-images.githubusercontent.com/83952803/231523806-c369289a-4e43-4f2c-bbc7-5e31a5f0df93.png)
![image](https://user-images.githubusercontent.com/83952803/231523904-f903ef52-d53a-4c64-bdcc-b549a31610de.png)
![image](https://user-images.githubusercontent.com/83952803/231524048-18ee0cd7-7034-4610-9433-584048f3b3d2.png)
![image](https://user-images.githubusercontent.com/83952803/231524160-f37fbffb-41c7-4e87-9094-0396dad4d297.png)
![image](https://user-images.githubusercontent.com/83952803/231524240-d05c023e-f06a-48e0-b2da-64395d6a3a2c.png)
![image](https://user-images.githubusercontent.com/83952803/231524407-e7fc0abe-2ff4-4878-ad4a-91549523c129.png)
![image](https://user-images.githubusercontent.com/83952803/231524490-6acfdda4-4264-4835-a338-70ece17e86db.png)
![image](https://user-images.githubusercontent.com/83952803/231524555-93a108f2-efde-4aa2-9404-724eca44c0dd.png)

2023-05-08 12:26 UTC, abhilash-aot approved these changes

2023-05-08 16:02 UTC, shuhaib-aot requested changes
Please resolve the conversations

2023-05-08 16:02 UTC, shuhaib-aot commented on forms-flow-web/src/modules/authorizationReducer.js
> +  userError: null,
is this variable contain only userError?

2023-05-08 16:02 UTC, shuhaib-aot commented on forms-flow-web/src/styles.scss
> +          background-color: #fc4f4f;
could you please check the color variable name is there in our code

2023-06-28 09:28 UTC, abhilash-aot commented
Point to develop branch and rebase to develop

2023-06-30 01:39 UTC, abhilash-aot approved these changes

2023-07-03 05:15 UTC, AbijithS-aot approved these changes

2023-07-03 15:39 UTC, merged