5.2.0 alpha
AOT-Technologies/forms-flow-ai pull request #1419
Opened 2023-05-10 07:26 UTC by abhilash-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2023-06-05 05:35 UTC, shuhaib-aot requested changes

2023-06-05 05:35 UTC, shuhaib-aot commented on .github/workflows/forms-flow-web-cd.yml
> +      - master
need to add develop also here. because later new code will merge to develop first. for testing and need to deploy this one as develop

2023-06-08 02:02 UTC, shuhaib-aot reviewed
LGTM

2023-06-16 09:33 UTC, shuhaib-aot approved these changes

2023-06-19 09:39 UTC, abilpraju-aot approved these changes

2023-06-20 12:09 UTC, merged