V4.0.3 pr 06 09
AOT-Technologies/forms-flow-ai pull request #142
Opened 2021-09-06 11:23 UTC by abhilash-aot

1. Added an env to save in local storage for Custom API 
2. Updated React child routes for 404
3.  Readme Updated for Custom Events in React/ Project Dependencies
4. Task list Pagination moved to server-side

2021-09-06 11:28 UTC, shibin-aot approved these changes
Looks good

2021-09-06 11:28 UTC, kurianbenoy-aot commented
@abhilash-aot requirement has been diverged from original develop branch.

 https://github.com/AOT-Technologies/forms-flow-ai-dev/tree/develop/forms-flow-api/requirements

2021-09-06 11:29 UTC, kurianbenoy-aot commented on forms-flow-api/requirements/dev.txt
> --r ./requirements.txt
Can't delete this file

2021-09-06 11:31 UTC, kurianbenoy-aot requested changes
It would be a good idea to double check if all the changes are there as expected. I found one file missing in python

2021-09-07 05:18 UTC, abhilash-aot commented on forms-flow-api/requirements/dev.txt
> --r ./requirements.txt
added back

2021-09-07 05:19 UTC, kurianbenoy-aot approved these changes

2021-09-07 23:36 UTC, merged