Add Kafka Producer as Execution Listener
AOT-Technologies/forms-flow-ai pull request #1427
Opened 2023-05-23 20:33 UTC by aurelio-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2023-05-25 10:26 UTC, SnehaSuresh-aot requested changes
Its better to use `org.apache.commons.lang3.StringUtils`  instead of adding a new dependency

2023-05-25 20:07 UTC, aurelio-aot commented on forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/execution/KafkaProducerListener.java
> +import org.apache.commons.lang.StringUtils;
@SnehaSuresh-aot - new commit is now pushed to address this comment

2023-05-30 14:16 UTC, auslin-aot reviewed
Just asking with curiosity the kafka consumer also will be added as a listener right?

2023-05-30 18:16 UTC, aurelio-aot commented
> Just asking with curiosity the kafka consumer also will be added as a listener right?

i honestly have not figured/decided that out yet, because a kafka consumer is a listener on a kafka topic as opposed to being a listener of a camunda process task, feel free to let me know what you think the kafka consumer should be, any suggestions/help would be highly appreciated, thanks.

2023-05-31 13:06 UTC, auslin-aot commented
> > Just asking with curiosity the kafka consumer also will be added as a listener right?
> 
> i honestly have not figured/decided that out yet, because a kafka consumer is a listener on a kafka topic as opposed to being a listener of a camunda process task, feel free to let me know what you think the kafka consumer should be, any suggestions/help would be highly appreciated, thanks.

Using the consumer as a  Listener on Kafka Topic will be good. Maybe we can capture future discussion points in the ticket https://aottech.atlassian.net/browse/FWF-2188.

2023-05-31 13:07 UTC, auslin-aot approved these changes

2023-06-05 00:27 UTC, aurelio-aot commented
Hi @abhilash-aot @SnehaSuresh-aot @auslin-aot -- added codes and documentation for the KafkaConsumerListener, kindly review.  Thanks.

2023-06-05 14:18 UTC, SnehaSuresh-aot approved these changes

2023-06-12 05:03 UTC, abhilash-aot approved these changes

2023-06-12 06:24 UTC, sumesh-aot approved these changes

2023-06-16 07:30 UTC, merged