added text translation for dmn
AOT-Technologies/forms-flow-ai pull request #1610
Opened 2023-09-06 08:38 UTC by abilpraju-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE
https://aottech.atlassian.net/browse/FWF-2437
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/83952803/62745854-60f2-478f-ba57-5391452f6018)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/83952803/0c7ef0e1-bade-4e86-b188-ad7fccd3038b)

2023-09-06 08:44 UTC, Josephalexantony-aot approved these changes

2023-09-12 07:49 UTC, shuhaib-aot requested changes

2023-09-12 07:49 UTC, shuhaib-aot commented on forms-flow-web/src/resourceBundles/formio_resourceBundles.js
> +    "Applicable for Client and Reviewer Roled Users only.": "Gilt nur für Benutzer mit Kunden- und Prüferrollen.",
is this translation is related formio or our application? if it is based on us then please give move this to micro-front-end repo

2023-09-12 08:14 UTC, shuhaib-aot approved these changes

2023-09-12 13:18 UTC, abhilash-aot approved these changes

2023-09-12 13:20 UTC, merged