Internationalisation updates
AOT-Technologies/forms-flow-ai pull request #1703
Opened 2023-11-09 16:46 UTC by Ajay-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes
Internationalisation updates for new UI changes

# Screenshots (if applicable)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/115780710/6e61aa5e-5f6b-4e5c-bb4a-0b212783d717)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/115780710/df33f922-548b-4ac0-a53e-4b97ad697a9e)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/115780710/23d16954-9ace-42c0-966f-c913aef78891)

2023-11-10 12:02 UTC, abilpraju-aot approved these changes

2023-11-10 12:04 UTC, Bonymol-aot approved these changes

2023-11-13 04:36 UTC, fahad-aot approved these changes

2023-11-13 05:21 UTC, shuhaib-aot requested changes
remove package-lock

2023-11-13 08:00 UTC, closed without merging