Expand all issue in tasklist  fixed
AOT-Technologies/forms-flow-ai pull request #1804
Opened 2023-12-13 17:57 UTC by fahad-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-2831
Issue Type: BUG/ FEATURE

# Changes
1.Expand all for task variable issue fixed

# Screenshots (if applicable)

2023-12-14 05:40 UTC, shuhaib-aot requested changes
please fix he edge case also if there is no variable to show in expanded row then currently some blank space are showing right. so if there is no data is there stick on the current row no need to expand 
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/95394061/1b67baac-fcba-416f-9d90-057ef0a89bfe)

2023-12-14 05:40 UTC, shuhaib-aot commented on forms-flow-web/src/components/ServiceFlow/list/ServiceTaskListView.js
>          updatedExpandedTasks[task.id] = newExpandedState;
what is newExpanded state

2023-12-14 10:55 UTC, fahad-aot commented
> please fix he edge case also if there is no variable to show in expanded row then currently some blank space are showing right. so if there is no data is there stick on the current row no need to expand ![image](https://private-user-images.githubusercontent.com/95394061/290415174-1b67baac-fcba-416f-9d90-057ef0a89bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTE0MzIsIm5iZiI6MTcwMjU1MTEzMiwicGF0aCI6Ii85NTM5NDA2MS8yOTA0MTUxNzQtMWI2N2JhYWMtZmNiYS00MTZmLTlkOTAtMDU3ZWYwYTg5YmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OTcyNThiMjU4YTY0NDM4ZmNmMTExOWY2Njg3ZTdmZWQwZjA1ZjlkNGNiNTBhYmNkYTg4MGNjOWExM2EyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.37he-4UJEW7yZy0pxA7uWN8JR9o_ZLBOwgzYy_dloNI)

![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/99656326/a4c297b6-9cdb-4dda-85b1-741e96741e5b)
fixed

2023-12-18 07:48 UTC, shuhaib-aot approved these changes

2023-12-19 05:00 UTC, abilpraju-aot approved these changes

2023-12-19 05:00 UTC, abilpraju-aot reviewed
resolve conflicts

2024-01-01 05:41 UTC, merged