function added for excluding internal workflow in workflow select
AOT-Technologies/forms-flow-ai pull request #2034
Opened 2024-05-05 16:21 UTC by Ajay-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-2796
Issue Type: BUG/ FEATURE

# Changes
function added for excluding internal workflow in workflow select and included in proccess page 

# Screenshots (if applicable)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/115780710/bd60c7b6-74e5-42bb-a489-a6cfee6f3458)
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/115780710/2ae2e0f8-5826-4335-9e24-451f0be3cabb)

2024-05-06 05:24 UTC, abilpraju-aot commented on forms-flow-web/src/components/Form/Steps/WorkFlow.js
> +              console.log("haaaaaaaai");
remove the console

2024-05-06 05:34 UTC, Ajay-aot commented on forms-flow-web/src/components/Form/Steps/WorkFlow.js
> +              console.log("haaaaaaaai");
removed

2024-05-09 09:59 UTC, shuhaib-aot requested changes

2024-05-09 16:06 UTC, Ajay-aot commented on forms-flow-web/src/components/Form/Steps/WorkFlow.js
> +              dispatch(setAllProcessList([]));
added properly

2024-05-13 05:15 UTC, fahad-aot approved these changes

2024-05-13 05:40 UTC, shuhaib-aot commented on forms-flow-web/src/components/Form/Steps/WorkFlow.js
> +              dispatch(setAllProcessList([]));
before which api we used to list the bpm process ?

2024-05-14 10:45 UTC, Ajay-aot commented on forms-flow-web/src/components/Form/Steps/WorkFlow.js
> +              dispatch(setAllProcessList([]));
modification added in bpm process listing api

2024-05-20 04:54 UTC, shuhaib-aot approved these changes

2024-05-20 04:54 UTC, merged