FWF-3319: [Added] Spanish resource bundle
AOT-Technologies/forms-flow-ai pull request #2049
Opened 2024-05-16 10:06 UTC by shuhaib-aot

# Issue Tracking

JIRA:  FWF3319
Issue Type: BUG/ FEATURE

# Changes
-  Added Spanish resource bundle
-  removed unwanted files of resource bundle
-  changed version to 6.0.1

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2024-05-16 10:18 UTC, abilpraju-aot approved these changes

2024-05-16 10:32 UTC, arun-s-aot approved these changes

2024-05-16 10:34 UTC, arun-s-aot requested changes
Can you update the date mentioned in changelog file from
## 6.0.1 - 2024-16-05
to 
## 6.0.1 - 2024-05-16

2024-05-16 10:36 UTC, shuhaib-aot commented
Sure

2024-05-16 10:36 UTC, auslin-aot commented on forms-flow-web/src/resourceBundles/formio_resourceBundles.js
> + "Dashbaord": "Panel de control",
please check it is misspelled?

2024-05-16 11:37 UTC, auslin-aot approved these changes

2024-05-17 05:29 UTC, arun-s-aot approved these changes

2024-05-17 05:58 UTC, merged