FWF-3349:[Bugfix] unwanted style removed
AOT-Technologies/forms-flow-ai pull request #2069
Opened 2024-05-27 17:11 UTC by Ajay-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes
unwanted style removed

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2024-05-28 01:37 UTC, Josephalexantony-aot approved these changes

2024-05-28 02:40 UTC, shuhaib-aot requested changes
Is this pull request necessary? We already have another one with these changes.
https://github.com/AOT-Technologies/forms-flow-ai-ee/pull/522/files

2024-05-28 05:34 UTC, Ajay-aot commented
> Is this pull request necessary? We already have another one with these changes. https://github.com/AOT-Technologies/forms-flow-ai-ee/pull/522/files

the removed class is added in mf in this pr
https://github.com/AOT-Technologies/forms-flow-ai-micro-front-ends/pull/205
thats why the class is removed from open source too

2024-05-29 06:01 UTC, shuhaib-aot approved these changes

2024-05-29 06:01 UTC, merged