updated with modal on downloading dmn and bpmn
AOT-Technologies/forms-flow-ai pull request #2282
Opened 2024-10-18 06:44 UTC by abilpraju-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE
https://aottech.atlassian.net/browse/FWF-3759
https://aottech.atlassian.net/browse/FWF-3760
https://jam.dev/c/7c18285d-6aa0-46a9-965c-3032fec7f9a9
# Changes

# Screenshots (if applicable)

# Notes

# Checklist
- [ ] Updated changelog
- [ ] Added meaningful title for pull request

2024-10-18 08:06 UTC, shuhaib-aot requested changes

2024-10-18 08:06 UTC, shuhaib-aot commented on forms-flow-web/src/components/Modeler/Editors/BpmnEditor/index.js
> +    // Check for linting errors in the modeler view
don't write any function inside this component please make sure the bpmn editor is reusable component only pass the xml and error setting function, and you can pass the ref and take the xml data by calling getBpmnModler function using this ref @abilpraju-aot  so please rework this part

2024-10-24 05:48 UTC, arun-s-aot commented on forms-flow-web/src/components/Modals/ActionModal.js
> +                                    icon={<CloseIcon color="#253DF4" />}
in the entire file , wherever we have added color="#253DF4" , please replace with css variable 
var(--ff-base-600) . It is present in entire page. 
Also if we dont have classNames to add , we can remove it from all the CustomButtons in this page 

@abilpraju-aot

2024-10-24 09:23 UTC, arun-s-aot approved these changes

2024-10-24 09:29 UTC, arun-s-aot commented
@abilpraju-aot Please remove the className="" attribute also as per previous comment

2024-10-24 10:02 UTC, auslin-aot approved these changes

2024-10-24 10:03 UTC, auslin-aot commented on forms-flow-web/src/apiManager/services/processServices.js
>    let url = replaceUrl(api, "<process_key>", process_key);
please remove console

2024-10-24 10:12 UTC, arun-s-aot approved these changes

2024-10-24 10:30 UTC, merged