New docker-compose file for Redis: Resolving port allocated issue
AOT-Technologies/forms-flow-ai pull request #2314
Opened 2024-10-29 06:11 UTC by alanraju-aot

# Issue Tracking

JIRA: 
https://aottech.atlassian.net/browse/FWF-3476

# Changes

# Screenshots (if applicable)

# Notes

# Checklist
- [ ] Updated changelog
- [ ] Added meaningful title for pull request

2024-10-30 08:43 UTC, kiran-aot requested changes
![Screenshot 2024-10-30 at 1 38 36 AM](https://github.com/user-attachments/assets/aba7ae0b-4f5a-4341-aac4-d3dc10841ff9)

Please review the documents-api compose file and remove the depends_on directive for Redis. Since this file does not include a Redis container (as it's managed separately), depends_on will not work as expected.

Consider using an alternative method, such as a health check, to ensure Redis is up before starting the document and web APIs. This could be done by adding a script that waits for Redis to be available or configuring a retry mechanism within the application itself.

2024-11-11 04:33 UTC, alanraju-aot commented
> ![Screenshot 2024-10-30 at 1 38 36 AM](https://private-user-images.githubusercontent.com/77142423/381459397-aba7ae0b-4f5a-4341-aac4-d3dc10841ff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTcyNDUsIm5iZiI6MTczMTI5Njk0NSwicGF0aCI6Ii83NzE0MjQyMy8zODE0NTkzOTctYWJhN2FlMGItNGY1YS00MzQxLWFhYzQtZDNkYzEwODQxZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDAzNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2IxYzk3NDJlNjhiZDA4ZmE5N2FmOWU1ODk0OTQ0MzRlZjFlZTc1YjUzM2Y1NzU1NWFkZTdjOTlkNmE5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RcIQR02znlZQOkzSnSE4mBDNQp6arlaR_wMZgK6nnAI)
> 
> Please review the documents-api compose file and remove the depends_on directive for Redis. Since this file does not include a Redis container (as it's managed separately), depends_on will not work as expected.
> 
> Consider using an alternative method, such as a health check, to ensure Redis is up before starting the document and web APIs. This could be done by adding a script that waits for Redis to be available or configuring a retry mechanism within the application itself.

done

2024-11-11 09:19 UTC, arun-s-aot approved these changes

2024-11-14 11:19 UTC, kiran-aot approved these changes

2024-11-14 11:29 UTC, merged