Feature/fwf 3736 preview page
AOT-Technologies/forms-flow-ai pull request #2336
Opened 2024-11-08 16:51 UTC by Ajay-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-3736
Issue Type: BUG/ FEATURE

# Changes
added form and workflow  preview page for users with view design permisson only

# Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/9c7e265f-a9b6-417c-9668-4302eab92bea)
![image](https://github.com/user-attachments/assets/296b572a-7f49-499d-868b-20be4afd0804)

# Checklist
- [ ] Updated changelog
- [ ] Added meaningful title for pull request

2024-11-11 03:50 UTC, arun-s-aot approved these changes

2024-11-11 04:19 UTC, shuhaib-aot requested changes
there are couple of changes.
1. if there is no designer permission for flow render diagram preview component 
2. if there is no designer permission for form render interactive form component

2024-11-11 04:19 UTC, shuhaib-aot commented on forms-flow-web/src/components/Form/EditForm/FormEdit.js
> +                          form={form}
need to pass options too

2024-11-11 04:19 UTC, shuhaib-aot commented on forms-flow-web/src/components/Form/EditForm/FormEdit.js
> +                          form={form}
in options need to pass lang

2024-11-11 14:49 UTC, Ajay-aot commented on forms-flow-web/src/components/Form/EditForm/FormEdit.js
> +                          form={form}
added

2024-11-11 14:54 UTC, Bonymol-aot approved these changes

2024-11-11 16:13 UTC, arun-s-aot commented
Please chjeck sonarcloud issue @Ajay-aot

2024-11-12 06:43 UTC, arun-s-aot commented
Sonar cloud issues to be taken care in @Josephalexantony-aot  commit. Merging the PR for now @Ajay-aot

2024-11-13 06:43 UTC, arun-s-aot approved these changes

2024-11-13 07:05 UTC, merged