Update pr-notification.yml
AOT-Technologies/forms-flow-ai pull request #2339
Opened 2024-11-11 07:07 UTC by sinto-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

# Screenshots (if applicable)

# Notes

# Checklist
- [ ] Updated changelog
- [ ] Added meaningful title for pull request

2024-11-11 07:54 UTC, shuhaib-aot approved these changes

2024-11-11 08:10 UTC, shuhaib-aot requested changes
no need to remove user image

2024-11-11 17:18 UTC, arun-s-aot approved these changes

2024-11-12 04:20 UTC, shuhaib-aot approved these changes

2024-11-12 04:20 UTC, merged