Fwf1064 internationalization (#1)
AOT-Technologies/forms-flow-ai pull request #322
Opened 2022-04-26 09:13 UTC by Bonymol-aot

Added internationalization for forms-flow-web

# Issue Tracking

JIRA: 
Issue Type: FEATURE

Added languages : Chinese , Portuguese , French , Bulgarian and German

# Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/88372115/165265769-cc13280b-a33a-4ae8-8b94-fede57aeb28d.png)
![image](https://user-images.githubusercontent.com/88372115/165265957-62f648fc-205b-43cb-9728-e1fdfb2e5fe3.png)

2022-04-26 10:35 UTC, abilpraju-aot reviewed
Build check failing please have a look

2022-04-26 12:08 UTC, abilpraju-aot approved these changes

2022-04-27 10:55 UTC, abhilash-aot requested changes

2022-04-27 10:55 UTC, abhilash-aot commented on deployment/docker/bundle/README.md
> +<<<<<<< HEAD
there are conflicts and please update the PR to include only the translation Changes

2022-04-27 11:26 UTC, closed without merging