Form Adapter
AOT-Technologies/forms-flow-ai pull request #633
Opened 2022-07-20 06:34 UTC by auslin-aot

# Issue Tracking

JIRA: 
Issue Type: FEATURE  :sparkles:
https://aottech.atlassian.net/browse/FWF-1446

2022-07-20 07:13 UTC, AbijithS-aot approved these changes

2022-07-20 11:40 UTC, shibin-aot requested changes
I added the changes, also FormBpm and FormBpmFiltered and FormConnecter is pending

2022-07-20 11:40 UTC, shibin-aot commented on deployment/docker/sample.env
> +CUSTOM_SUBMISSION_URL=custom_url
give a sample url if possible to help user configure it

2022-07-20 11:40 UTC, shibin-aot commented on forms-flow-bpm/sample.env
> +CUSTOM_SUBMISSION_URL=custom_url
same here

2022-07-20 11:40 UTC, shibin-aot commented on forms-flow-bpm/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java
> +    private boolean enableCustomSubmission;
use integrationCredentialProperties to access this

2022-07-20 11:40 UTC, shibin-aot commented on forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners/BPMFormDataPipelineListener.java
> +    @Value("${formsflow.ai.enableCustomSubmission}")
integrationCredentialProperties - can be used

2022-07-20 11:40 UTC, shibin-aot commented on forms-flow-bpm/src/main/resources/application.yaml
> +  enableCustomSubmission: ${CUSTOM_SUBMISSION_ENABLED}
you can create a subproperty called forms and place the new properties under it. Make more sense

2022-07-21 09:56 UTC, AbijithS-aot approved these changes

2022-07-25 10:14 UTC, auslin-aot commented
Updated in https://github.com/AOT-Technologies/forms-flow-ai/pull/669

2022-07-25 10:14 UTC, closed without merging