Bpmn modeller UI changes
AOT-Technologies/forms-flow-ai pull request #717
Opened 2022-08-04 18:43 UTC by devin-aot

# Issue Tracking

JIRA: https://aottech.atlassian.net/browse/FWF-1586
Issue Type: BUG/ FEATURE

# Changes
UI changes from markups:
[](https://xd.adobe.com/view/04320d3f-50b2-4088-9878-ce1d63fb0942-5161/screen/d9f4560a-add4-4fea-8024-8ae3e8a7f200)

Includes:
- Show non-executable processes in dropdown
- Include option to show Internal processes in dropdown (in source code, not ui)
- Dropdown height extends when modeller is shown
- Trash icon set to visible
- Max height set for canvas
- Added "Help" button that redirects to camunda documentation

2022-08-08 20:02 UTC, sumesh-aot approved these changes

2022-08-09 00:02 UTC, sreehari-aot requested changes

2022-08-09 15:23 UTC, devin-aot commented on forms-flow-web/src/apiManager/services/processServices.js
> +    httpGETRequest(API.GET_BPM_PROCESS_LIST + `?latestVersion=true&excludeInternal=${excludeInternal}`, {}, UserService.getToken(), true)
Will do. I didn't see these rules on the master branch, could we copy the contributing.md from the develop branch to the master?

2022-08-09 15:39 UTC, sreehari-aot commented on forms-flow-web/src/apiManager/services/processServices.js
> +    httpGETRequest(API.GET_BPM_PROCESS_LIST + `?latestVersion=true&excludeInternal=${excludeInternal}`, {}, UserService.getToken(), true)
We will go for a release this month.

2022-08-11 05:26 UTC, abhilash-aot approved these changes

2022-08-11 05:47 UTC, sreehari-aot approved these changes

2022-08-11 06:05 UTC, abhilash-aot approved these changes

2022-08-11 06:05 UTC, abhilash-aot commented on forms-flow-web/src/apiManager/endpoints/index.js
> +  GET_BPM_DEPLOYMENTS: `${BPM_BASE_URL}/deployment`,
@

2022-08-11 06:05 UTC, abhilash-aot commented on forms-flow-web/src/apiManager/endpoints/index.js
> +  GET_BPM_DEPLOYMENTS: `${BPM_BASE_URL}/deployment`,
@SnehaSuresh-aot Check if deployment APIs need to be added to bpm gateway

2022-08-11 06:05 UTC, merged