Changes for passing x-jwt-token in response header
AOT-Technologies/forms-flow-ai pull request #721
Opened 2022-08-05 20:40 UTC by sumesh-aot

# Issue Tracking

JIRA: 
https://aottech.atlassian.net/browse/FWF-1588

# Changes

# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

# Notes

2022-08-05 20:53 UTC, sumesh-aot commented
Changes on web is needed. Can someone else do that ? @sreehari-aot @shuhaib-aot @AbijithS-aot ?

2022-08-06 03:12 UTC, sreehari-aot approved these changes
LGTM!

2022-08-06 05:23 UTC, alanraju-aot approved these changes

2022-08-08 06:00 UTC, shuhaib-aot commented
> Changes on web is needed. Can someone else do that ? @sreehari-aot @shuhaib-aot @AbijithS-aot ?

 I will do that

2022-08-08 07:25 UTC, abhilash-aot requested changes
Need to revert removal of JWT key env from web (else current develop will break). Also add tenant key in generation of jwt token in multitenant time

2022-08-08 07:27 UTC, abhilash-aot commented on forms-flow-api/src/formsflow_api/resources/formio.py
> +                "user": {"_id": unique_user_id, "roles": _role_ids},
project is a optional param , cannot pass null. project id is given in case of enterprise

2022-08-08 16:44 UTC, sumesh-aot commented on forms-flow-web/docker-compose.yml
> -        - REACT_APP_FORMIO_JWT_SECRET=${FORMIO_JWT_SECRET:---- change me now ---}
Ok, I think we can time merging both PRs.

2022-08-08 16:46 UTC, sumesh-aot commented on forms-flow-api/src/formsflow_api/resources/formio.py
> +                "user": {"_id": unique_user_id, "roles": _role_ids},
In web code, I saw passing project id always. In backend we will have the project URL as the default formio URL, so it's safe to keep there. For multi tenant, it's another PR in admin repo, I will make that changes there.

2022-08-08 16:48 UTC, sumesh-aot commented on forms-flow-api/src/formsflow_api/resources/formio.py
> +                "user": {"_id": unique_user_id, "roles": _role_ids},
@abhilash-aot https://github.com/AOT-Technologies/forms-flow-ai-admin/pull/11

2022-08-09 07:15 UTC, abhilash-aot commented on forms-flow-web/docker-compose.yml
> -        - REACT_APP_FORMIO_JWT_SECRET=${FORMIO_JWT_SECRET:---- change me now ---}
Ok👍

2022-08-09 07:16 UTC, abhilash-aot commented on forms-flow-api/src/formsflow_api/resources/formio.py
> +                "user": {"_id": unique_user_id, "roles": _role_ids},
https://github.com/AOT-Technologies/forms-flow-ai/blob/5f14a8b09c1fcbffee56eca4b286ab3f19c42b6b/forms-flow-web/src/services/UserService.js#L180 project id isn't available in current code.

2022-08-09 07:24 UTC, sumesh-aot commented on forms-flow-api/src/formsflow_api/resources/formio.py
> +                "user": {"_id": unique_user_id, "roles": _role_ids},
pushed the changes

2022-08-09 07:40 UTC, abhilash-aot approved these changes
@shuhaib-aot please merge your web changes branch for token removal with this PR to develop and check once

2022-08-09 08:31 UTC, sreehari-aot approved these changes
LGTM

2022-08-09 16:01 UTC, sumesh-aot commented
@abhilash-aot @shuhaib-aot let's merge the changes after the sprint review.

2022-08-10 18:33 UTC, merged