Draft count
AOT-Technologies/forms-flow-ai pull request #727
Opened 2022-08-08 11:44 UTC by seethalelias-aot

Added draft count to the application endpoint.

2022-08-08 12:11 UTC, sreehari-aot reviewed
add / update the test cases as well

2022-08-08 12:11 UTC, sreehari-aot commented on forms-flow-api/src/formsflow_api/models/application.py
> +            Application.application_status == DRAFT_APPLICATION_STATUS
need to fetch the count for active drafts only, add that too

2022-08-08 12:11 UTC, sreehari-aot commented on forms-flow-api/src/formsflow_api/models/application.py
> +            Application.application_status == DRAFT_APPLICATION_STATUS
same

2022-08-08 12:11 UTC, sreehari-aot commented on forms-flow-api/src/formsflow_api/models/application.py
> +            Application.application_status == DRAFT_APPLICATION_STATUS
same

2022-08-10 07:01 UTC, abhilash-aot approved these changes
Any changes need in frontend @sreehari-aot

2022-08-10 08:12 UTC, sreehari-aot commented
can u attach a response screenshot

2022-08-10 08:21 UTC, AbijithS-aot approved these changes

2022-08-10 08:48 UTC, sreehari-aot approved these changes

2022-08-10 08:50 UTC, auslin-aot approved these changes

2022-08-10 08:53 UTC, sreehari-aot requested changes
correction needed

2022-08-10 13:44 UTC, sreehari-aot approved these changes

2022-08-11 04:48 UTC, merged