formsflowdocument code cleanup
AOT-Technologies/forms-flow-ai pull request #809
Opened 2022-08-26 07:47 UTC by seethalelias-aot

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes
1. Remove unwanted  folder
2. Add missing values to the docker file and sample.env
3. Formatted using isort and black

2022-08-26 08:01 UTC, abhilash-aot requested changes

2022-08-26 08:11 UTC, ratheesh-aot approved these changes

2022-08-26 08:23 UTC, seethalelias-aot commented on forms-flow-documents/docker-compose.yml
> +      WEB_API_BASE_URL: ${DOCUMENT_SERVICE_URL}
FORMFLOW_API_URL pointing to  webapi. will change the name WEB_API_BASE_URL. to another meaningful name.

2022-08-26 11:12 UTC, abhilash-aot commented on forms-flow-documents/docker-compose.yml
> +      WEB_API_BASE_URL: ${DOCUMENT_SERVICE_URL}
Ok👍

2022-08-28 05:15 UTC, abhilash-aot approved these changes

2022-08-28 05:15 UTC, merged