Fwf 1690
AOT-Technologies/forms-flow-ai pull request #903
Opened 2022-09-19 06:35 UTC by AbijithS-aot

* new end point added for form submission

# Issue Tracking

JIRA: 
Issue Type: BUG/ FEATURE

# Changes

new end point added for application create
# How has the change been tested?

# Screenshots (if applicable)

# Build Success screenshot (Till a CICD pipeline is set up)

![image](https://user-images.githubusercontent.com/98075058/190961377-998410b5-2cdc-43c6-bc2b-d67645c535fc.png)

# Notes

2022-09-19 06:50 UTC, Josephalexantony-aot approved these changes

2022-09-19 15:15 UTC, sreehari-aot requested changes

2022-09-19 15:15 UTC, sreehari-aot commented on forms-flow-api-utils/src/formsflow_api_utils/services/external/formio.py
> +from xmlrpc.client import ResponseError
unused import

2022-09-19 15:32 UTC, abilpraju-aot approved these changes

2022-09-19 17:11 UTC, sumesh-aot requested changes
Test cases are missing.

2022-09-19 17:11 UTC, sumesh-aot commented on forms-flow-api/src/formsflow_api/resources/application.py
> +@API.route("/create-application", methods=["POST", "OPTIONS"])
This is not an acceptable rest endpoint, as `/application/create` is already there, and `/application/create-application` doesn't follow rest standard.
May be make it as `/application/external/create` or something to align with other endpoint pattern we are following

2022-09-19 17:11 UTC, sumesh-aot commented on forms-flow-api/docker-compose.yml
> +      WEB_BASE_URL: ${WEB_BASE_URL}
Can you add a default null value here to break existing applications ?

2022-09-19 17:11 UTC, sumesh-aot commented on forms-flow-api/src/formsflow_api/resources/application.py
> +            dict_data = application_schema.load(application_json)
Please provide meaningful name instead of dict_data, like is it application_data ?

2022-09-27 17:24 UTC, sumesh-aot commented
@AbijithS-aot Can you please make the requested changes and update the PR ?

2022-09-28 15:26 UTC, AbijithS-aot commented
will update test case in another pr

2022-09-29 04:46 UTC, sumesh-aot commented
@AbijithS-aot Can you change the target repo to release/5.0.1 ?

2022-09-29 05:10 UTC, auslin-aot commented on forms-flow-api/docker-compose.yml
> +      WEB_BASE_URL: ${WEB_BASE_URL:-null}
can you pls add WEB_BASE_URL in sample.env

2022-09-29 10:41 UTC, closed without merging